- hosts: all
  tasks:
  - name: Install ntpd
    yum: 
      name: ntp
      state: latest
- hosts: web
  tasks:
  - name: Install Apache
    yum:
      name: httpd
      state: latest
- hosts: db
  tasks:
  - name: Install MySQl
    yum:
      name: mariadb-server
      state: latest
        
