- hosts: all
  tasks:
  - name: Install ntpd
    package: 
      name: ntp
      state: latest
  - name: Reconfigure time servers
    lineinfile:
      path: /etc/ntp.conf
      regexp: '^server.*iburst$'
      line: 'server pool.ntp.org iburst'
    notify: Restart ntpd
  - name: Delete unused time servers
    lineinfile:
      path: /etc/ntp.conf
      regexp: "^server [0,1,2,3].*iburst$"
      state: absent
      backup: yes
    notify: Restart ntpd
  handlers:
  - name: Restart ntpd
    service:
      name: ntpd
      state: restarted