- hosts: web
  tasks:
  - name: Restart all services
    shell: echo "Restarting all services"
    notify: restart-all
  handlers:
  - name: Restart sshd
    service:
      name: sshd
      state: restarted
      enabled: yes
    listen: "restart-all"
  - name: Restart ntpd
    service:
      name: ntpd
      state: restarted
      enabled: yes
    listen: "restart-all"